"""baseline schema

Revision ID: 2df7c70dd3c9
Revises: 
Create Date: 2026-06-08 09:31:59.567343
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # custom UTCDateTime type used in the columns below


revision: str = '2df7c70dd3c9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event'), ['event'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_agent', sa.String(length=60), nullable=False),
    sa.Column('to_agent', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('group_slug', sa.String(length=61), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('in_reply_to', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('delivered_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.core.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation', ['from_agent', 'to_agent', 'created_at'], unique=False)
        batch_op.create_index('ix_messages_pending', ['to_agent', 'delivered_at'], unique=False)
        batch_op.create_index('ix_messages_thread', ['thread_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.core.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agents',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('allowed_senders', sa.JSON(), nullable=True),
    sa.Column('max_auto_per_hour', sa.Integer(), nullable=False),
    sa.Column('auto_timeout_secs', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('groups',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', app.core.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)

    op.create_table('agent_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_slug', sa.String(length=60), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.core.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_slug'], ['agents.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_keys_agent_slug'), ['agent_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('group_members',
    sa.Column('group_slug', sa.String(length=60), nullable=False),
    sa.Column('agent_slug', sa.String(length=60), nullable=False),
    sa.Column('added_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_slug'], ['agents.slug'], ),
    sa.ForeignKeyConstraint(['group_slug'], ['groups.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_slug', 'agent_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    with op.batch_alter_table('agent_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_keys_agent_slug'))

    op.drop_table('agent_keys')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    op.drop_table('groups')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_thread')
        batch_op.drop_index('ix_messages_pending')
        batch_op.drop_index('ix_messages_conversation')

    op.drop_table('messages')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_event'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
