"""agent filesystem guardrails

Revision ID: f7d5aeb53fc5
Revises: 2df7c70dd3c9
Create Date: 2026-06-08 16:57:15.995095
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7d5aeb53fc5"
down_revision: str | None = "2df7c70dd3c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows (the agents table already has data
    # in deployed instances) with the safe defaults — same values the ORM uses.
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("allow_write", sa.Boolean(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.add_column(
            sa.Column(
                "block_hidden_files", sa.Boolean(), nullable=False, server_default=sa.text("1")
            )
        )
        batch_op.add_column(
            sa.Column(
                "block_sensitive_paths", sa.Boolean(), nullable=False, server_default=sa.text("1")
            )
        )
        batch_op.add_column(
            sa.Column("confine_to_dir", sa.Boolean(), nullable=False, server_default=sa.text("1"))
        )
        batch_op.add_column(
            sa.Column("denied_paths", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(
            sa.Column("trusted_senders", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_column("trusted_senders")
        batch_op.drop_column("denied_paths")
        batch_op.drop_column("confine_to_dir")
        batch_op.drop_column("block_sensitive_paths")
        batch_op.drop_column("block_hidden_files")
        batch_op.drop_column("allow_write")

    # ### end Alembic commands ###
